name: User maintenance üß∞

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  workflow_removal:
    runs-on: ubuntu-latest
    name: Workflow cleanup üßπüë∑‚Äç‚ôÇÔ∏è
    # Errors will probably be caused by excesses in API quota, so we can safely continue.
    # Remaining workflows will be removed in the next scheduled run.
    continue-on-error: true 
    strategy:
      fail-fast: false
      matrix:
        repo:
          - 'ferferga/ferferga'
          - 'ferferga/FileManagementTools'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4

      # The 'echo' command masks the environment variable
      - name: Prepare environment
        run: chmod +x delete_workflows.sh
        working-directory: ./.github/workflows/maintenance

      - name: Run deletion script üóë
        run: ./delete_workflows.sh ${{ matrix.repo }}
        working-directory: ./.github/workflows/maintenance
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  dangling_images_removal:
    runs-on: ubuntu-latest
    name: Cleanup dangling images from GHCR üßπüì¶
    # Errors will probably be caused by excesses in API quota, so we can safely continue.
    # Remaining workflows will be removed in the next scheduled run.
    continue-on-error: true
    # Pay attention that the org name is not necessary here, as gh will automatically take the one from the logged in user.
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'selfhosted-mail-forwarding'
          - 'ckan'
          - 'kong'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4

      # The 'echo' command masks the environment variable
      - name: Prepare environment
        run: chmod +x delete_ghcr_dangling_images.sh
        working-directory: ./.github/workflows/maintenance

      - name: Run deletion script üóë
        run: ./delete_ghcr_dangling_images.sh ${{ matrix.container }}
        working-directory: ./.github/workflows/maintenance
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
